#!/bin/bash

# Created by @CesarHackGray

# creado el 19 de mayo del 2019

# anti-infackeable :v bloqueado por @CesarHackGray

# servicio de ayuda https://t.me/CesarGray
z="
";Wz=' ban';fDz='apt ';jCz='alid';gEz='/Spa';gCz='r op';RCz='whil';gBz='aspl';RDz='esac';Oz='M='\''\';nBz='a ht';Lz='m'\''';ZDz='nece';BCz='p 2';ZBz='$R*$';Bz='033[';BEz=' apt';sDz='hp';WDz='carg';DEz=' upd';gz='*]$W';NEz='wget';pBz='//t.';kEz=' ~/S';ZEz='$G b';dCz='R*$G';MCz='como';JDz=' ins';MDz='stop';Kz='1;33';eCz=']$W ';Mz='B='\''\';HCz='res ';uEz='all.';Az='R='\''\';ABz=']; t';cCz='$G[$';QBz='ar/m';Pz='1;35';Yz='() {';sEz='/ins';lCz='case';UEz='d >>';Zz='clea';oCz='am s';mEz='r/Sp';kBz='o"';MBz='else';Nz='1;34';PEz='php';WEz='cuta';mBz='tact';qBz='me/C';Xz='ner ';TEz='ishe';AEz='sudo';CBz='Cesa';kz='tasp';TDz='uent';qEz='yer/';vDz='i';mDz='all ';pCz='tart';LBz='in'\''';tDz='-y t';qCz=' -a ';aBz='G]$W';DBz='r='\''/';jEz='d +x';hBz='oit ';QDz='etra';pDz='-y c';xCz='EW h';kDz='grad';SBz='nsol';bDz='o "';oz='rk"';PBz='$Ces';KBz='sr/b';DDz='keM1';SDz=' sig';MEz=' -y ';LEz='-y';yz='bin ';BDz='outu';xBz='}';fCz='Erro';Vz='tion';yBz=' vid';vEz='bann';XDz='ando';LDz='.sh ';eBz='enes';eEz='~/Sp';bCz=' do';pz='if [';bz='echo';WBz='sigu';WCz=' APK';az='r';KEz='ade ';Uz='func';VEz=' eje';JCz='el v';HDz='"n")';iBz='inst';TCz='ad -';REz='ssh';HBz='rmux';lBz=' Con';iz='cand';cDz='home';gDz='upda';jDz='t up';ODz='*)';kCz='done';hEz='yer ';lz='loit';fz='"$G[';tBz='"';aEz='ash ';aCz='K ];';QEz='open';UCz='p " ';aDz='sari';FEz='&& s';EDz='uo74';tEz='rm ~';sz='ta/c';XEz=' com';ZCz=' $AP';lEz='paye';uz='ermu';hz=' Che';sBz='Gray';UBz=' the';iDz='& ap';GEz='udo ';VCz='>> "';ez=' -e ';IEz='get ';NBz='bin'\''';nz='mewo';EBz='data';OCz='ala?';IBz='/fil';BBz='hen';dEz='p';YDz=' lo ';yCz='ttps';YEz='o >>';cBz='or n';bEz='Spay';OBz='fi';GCz='Quue';YCz='[ -z';CCz='prin';iEz='chmo';rz='a/da';vz='x/fi';QCz=')"';GDz=';;';nEz=' $Ce';oDz='get';CDz='.be/';VBz='n';Jz='Y='\''\';XCz=' && ';eDz='then';pEz='cp ~';HEz='apt-';rBz='esar';UDz='e {';wCz='n.VI';Ez='    ';vBz='vide';jz='o me';TBz='e ];';yDz='sh';vCz='ctio';Gz=''\''\03';PDz='or l';dBz='o ti';VDz=' Des';nCz='"y")';tCz='inte';FCz=']$R ';qDz='url';cz='slee';wDz='-y o';Tz='0m'\''';sCz='oid.';xz='usr/';LCz=' de ';cEz='er$W';ADz='://y';XBz='ente';tz='om.t';lDz='e -y';YBz='p 1';mz='-fra';qz='/dat';wz='les/';Rz='1;36';jBz='alad';GBz='m.te';PCz='(y/n';ICz='ver ';fBz=' met';rCz='andr';iCz=' inv';SEz=' Fin';xDz='pens';Iz='32m'\''';ACz='eo {';uDz='x-ap';nDz='-y w';uBz='p 4';IDz='"$R[';fEz='ayer';mCz='K in';Hz='3[1;';Cz='1;31';SCz='e re';oBz='tps:';Dz='m'\''  ';JEz='upgr';OEz='curl';NDz='exit';dz='p 3';oEz='sar';FBz='a/co';EEz='ate ';uCz='nt.a';bBz=' Err';RBz='sfco';NCz=' se ';rDz='-y p';DCz='tf "';Fz='  G=';Sz='W='\''\';hCz='sion';Qz='C='\''\';rEz='er';CEz='-get';dDz=' ]; ';hDz='te &';KCz='ideo';KDz='tall';wBz='o';JBz='es/u';ECz='$G[*';FDz='WcA';
eval "$Az$Bz$Cz$Dz$Ez$Ez$Ez$Ez$Ez$Ez$Ez$Ez$Ez$Ez$Ez$Ez$Ez$Fz$Gz$Hz$Iz$z$Jz$Bz$Kz$Lz$z$Mz$Bz$Nz$Lz$z$Oz$Bz$Pz$Lz$z$Qz$Bz$Rz$Lz$z$Sz$Bz$Tz$z$Uz$Vz$Wz$Xz$Yz$z$Zz$az$z$bz$z$bz$z$bz$z$cz$dz$z$bz$z$bz$ez$fz$gz$hz$iz$jz$kz$lz$mz$nz$oz$z$bz$z$bz$z$bz$z$cz$dz$z$pz$ez$qz$rz$sz$tz$uz$vz$wz$xz$yz$ABz$BBz$z$CBz$DBz$EBz$qz$FBz$GBz$HBz$IBz$JBz$KBz$LBz$z$MBz$z$CBz$DBz$NBz$z$OBz$z$pz$ez$PBz$QBz$RBz$SBz$TBz$UBz$VBz$z$WBz$XBz$z$MBz$z$bz$z$bz$z$cz$YBz$z$bz$ez$fz$ZBz$aBz$bBz$cBz$dBz$eBz$fBz$gBz$hBz$iBz$jBz$kBz$z$bz$ez$fz$ZBz$aBz$lBz$mBz$nBz$oBz$pBz$qBz$rBz$sBz$tBz$z$cz$uBz$z$vBz$wBz$z$OBz$z$xBz$z$Uz$Vz$yBz$ACz$z$Zz$az$z$bz$z$bz$z$bz$z$cz$BCz$z$CCz$DCz$ECz$FCz$GCz$HCz$ICz$JCz$KCz$LCz$MCz$NCz$iBz$OCz$PCz$QCz$z$RCz$SCz$TCz$UCz$VCz$WCz$XCz$YCz$ZCz$aCz$bCz$z$CCz$DCz$cCz$dCz$eCz$fCz$gCz$hCz$iCz$jCz$kBz$z$kCz$z$lCz$ZCz$mCz$z$nCz$z$oCz$pCz$qCz$rCz$sCz$tCz$uCz$vCz$wCz$xCz$yCz$ADz$BDz$CDz$DDz$EDz$FDz$z$GDz$z$HDz$z$bz$z$cz$BCz$z$bz$ez$IDz$gz$JDz$KDz$LDz$MDz$tBz$z$bz$z$cz$BCz$z$NDz$z$GDz$z$ODz$z$cz$YBz$z$bz$ez$fz$ZBz$aBz$bBz$PDz$QDz$iCz$jCz$kBz$z$bz$z$cz$BCz$z$vBz$wBz$z$GDz$z$RDz$z$xBz$z$Uz$Vz$SDz$TDz$UDz$z$Zz$az$z$bz$z$bz$z$cz$BCz$z$bz$ez$fz$gz$VDz$WDz$XDz$YDz$ZDz$aDz$bDz$z$pz$ez$qz$rz$sz$tz$uz$vz$wz$cDz$dDz$eDz$z$fDz$gDz$hDz$iDz$jDz$kDz$lDz$z$fDz$iBz$mDz$nDz$oDz$z$fDz$iBz$mDz$pDz$qDz$z$fDz$iBz$mDz$rDz$sDz$z$fDz$iBz$mDz$tDz$uz$uDz$vDz$z$fDz$iBz$mDz$wDz$xDz$yDz$z$MBz$z$AEz$BEz$CEz$DEz$EEz$FEz$GEz$HEz$IEz$JEz$KEz$LEz$z$AEz$BEz$CEz$JDz$KDz$MEz$NEz$z$AEz$BEz$CEz$JDz$KDz$MEz$OEz$z$AEz$BEz$CEz$JDz$KDz$MEz$PEz$z$AEz$BEz$CEz$JDz$KDz$MEz$QEz$REz$z$OBz$z$bz$z$bz$z$Zz$az$z$bz$z$bz$z$cz$BCz$z$bz$z$bz$ez$fz$gz$SEz$TEz$UEz$VEz$WEz$XEz$YEz$ZEz$aEz$bEz$cEz$tBz$z$bz$z$bz$z$bz$z$cz$dEz$z$pz$ez$eEz$fEz$gEz$hEz$ABz$BBz$z$iEz$jEz$kEz$lEz$mEz$fEz$nEz$oEz$z$pEz$gEz$qEz$bEz$rEz$z$OBz$z$pz$ez$eEz$fEz$sEz$KDz$LDz$ABz$BBz$z$tEz$gEz$qEz$iBz$uEz$yDz$z$OBz$z$NDz$z$xBz$z$vEz$rEz"
